// <auto-generated />
namespace ResumeBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
<<<<<<< HEAD:ResumeBuilder/ResumeBuilder/Migrations/202003230456518_DbSet-UserSkill.Designer.cs
    public sealed partial class DbSetUserSkill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbSetUserSkill));
        
        string IMigrationMetadata.Id
        {
            get { return "202003230456518_DbSet-UserSkill"; }
=======
    public sealed partial class changesineducationmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesineducationmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202003230957536_changes in education model "; }
>>>>>>> master:ResumeBuilder/ResumeBuilder/Migrations/202003230957536_changes in education model .Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
