// <auto-generated />
namespace ResumeBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changedtoandfromyeardatatypeinWorkExperiencemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtoandfromyeardatatypeinWorkExperiencemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202003231408005_changed to and from year data type in WorkExperience model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
